export const QUESTIONS = [
  // pop-culture
  { id: 'q001', category: 'pop-culture', text: 'Which streaming service produced "Stranger Things"?', options: ['Hulu', 'Netflix', 'Disney+', 'Amazon Prime'], correctIndex: 1 },
  { id: 'q002', category: 'pop-culture', text: 'Who played the Joker in "The Dark Knight"?', options: ['Joaquin Phoenix', 'Jared Leto', 'Heath Ledger', 'Jack Nicholson'], correctIndex: 2 },
  { id: 'q003', category: 'pop-culture', text: 'What is the best-selling music artist of all time?', options: ['Madonna', 'The Beatles', 'Elvis Presley', 'Michael Jackson'], correctIndex: 1 },
  { id: 'q004', category: 'pop-culture', text: 'Which fictional city does Batman protect?', options: ['Metropolis', 'Star City', 'Gotham City', 'Central City'], correctIndex: 2 },
  { id: 'q005', category: 'pop-culture', text: 'Which artist released the album "Lemonade"?', options: ['Rihanna', 'Beyoncé', 'Adele', 'Nicki Minaj'], correctIndex: 1 },
  { id: 'q006', category: 'pop-culture', text: 'What is the highest-grossing film of all time (unadjusted)?', options: ['Titanic', 'Avengers: Endgame', 'Avatar', 'Star Wars: The Force Awakens'], correctIndex: 2 },
  { id: 'q007', category: 'pop-culture', text: 'In "Friends", what is the name of Ross and Monica\'s pet monkey?', options: ['Marcel', 'George', 'Chandler', 'Gunther'], correctIndex: 0 },
  { id: 'q008', category: 'pop-culture', text: 'Which singer is known as the "Queen of Pop"?', options: ['Lady Gaga', 'Britney Spears', 'Madonna', 'Mariah Carey'], correctIndex: 2 },

  // history
  { id: 'q009', category: 'history', text: 'In what year did the Berlin Wall fall?', options: ['1987', '1991', '1989', '1993'], correctIndex: 2 },
  { id: 'q010', category: 'history', text: 'Who was the first President of the United States?', options: ['Thomas Jefferson', 'John Adams', 'George Washington', 'Benjamin Franklin'], correctIndex: 2 },
  { id: 'q011', category: 'history', text: 'Which empire built the Colosseum?', options: ['Greek', 'Roman', 'Ottoman', 'Persian'], correctIndex: 1 },
  { id: 'q012', category: 'history', text: 'In what year did World War II end?', options: ['1943', '1944', '1945', '1946'], correctIndex: 2 },
  { id: 'q013', category: 'history', text: 'Who was the famous queen of ancient Egypt who allied with Mark Antony?', options: ['Nefertiti', 'Hatshepsut', 'Cleopatra', 'Ankhesenamun'], correctIndex: 2 },
  { id: 'q014', category: 'history', text: 'Which country gifted the Statue of Liberty to the USA?', options: ['United Kingdom', 'Spain', 'France', 'Italy'], correctIndex: 2 },
  { id: 'q015', category: 'history', text: 'The Titanic sank in which year?', options: ['1905', '1912', '1918', '1923'], correctIndex: 1 },
  { id: 'q016', category: 'history', text: 'Who was the leader of the Soviet Union during the Cuban Missile Crisis?', options: ['Stalin', 'Khrushchev', 'Lenin', 'Gorbachev'], correctIndex: 1 },

  // sport
  { id: 'q017', category: 'sport', text: 'How many players are on a standard football (soccer) team on the pitch?', options: ['9', '10', '11', '12'], correctIndex: 2 },
  { id: 'q018', category: 'sport', text: 'In which sport would you perform a "slam dunk"?', options: ['Volleyball', 'Basketball', 'Tennis', 'Handball'], correctIndex: 1 },
  { id: 'q019', category: 'sport', text: 'How often are the Summer Olympic Games held?', options: ['Every 2 years', 'Every 3 years', 'Every 4 years', 'Every 5 years'], correctIndex: 2 },
  { id: 'q020', category: 'sport', text: 'Which country has won the most FIFA World Cups?', options: ['Germany', 'Argentina', 'Italy', 'Brazil'], correctIndex: 3 },
  { id: 'q021', category: 'sport', text: 'In tennis, what is a score of zero called?', options: ['Nil', 'Love', 'Zero', 'Nought'], correctIndex: 1 },
  { id: 'q022', category: 'sport', text: 'How many rings are on the Olympic flag?', options: ['4', '5', '6', '7'], correctIndex: 1 },
  { id: 'q023', category: 'sport', text: 'Which boxer was known as "The Greatest"?', options: ['Mike Tyson', 'Joe Frazier', 'Muhammad Ali', 'George Foreman'], correctIndex: 2 },
  { id: 'q024', category: 'sport', text: 'What is the maximum score possible with three darts in a single visit?', options: ['170', '180', '160', '150'], correctIndex: 1 },

  // science
  { id: 'q025', category: 'science', text: 'What is the chemical symbol for gold?', options: ['Go', 'Gd', 'Au', 'Ag'], correctIndex: 2 },
  { id: 'q026', category: 'science', text: 'What planet is known as the Red Planet?', options: ['Venus', 'Jupiter', 'Saturn', 'Mars'], correctIndex: 3 },
  { id: 'q027', category: 'science', text: 'What gas do plants primarily absorb from the atmosphere?', options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'], correctIndex: 2 },
  { id: 'q028', category: 'science', text: 'How many bones are in the adult human body?', options: ['186', '206', '226', '246'], correctIndex: 1 },
  { id: 'q029', category: 'science', text: 'What is the speed of light approximately?', options: ['300,000 km/s', '150,000 km/s', '3,000 km/s', '30,000 km/s'], correctIndex: 0 },
  { id: 'q030', category: 'science', text: 'Who developed the theory of general relativity?', options: ['Isaac Newton', 'Niels Bohr', 'Albert Einstein', 'Stephen Hawking'], correctIndex: 2 },
  { id: 'q031', category: 'science', text: 'What is the powerhouse of the cell?', options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Golgi apparatus'], correctIndex: 2 },
  { id: 'q032', category: 'science', text: 'Which element has the atomic number 1?', options: ['Helium', 'Hydrogen', 'Oxygen', 'Carbon'], correctIndex: 1 },

  // food-drink
  { id: 'q033', category: 'food-drink', text: 'Which spirit is the base of a traditional Mojito?', options: ['Vodka', 'Gin', 'White rum', 'Tequila'], correctIndex: 2 },
  { id: 'q034', category: 'food-drink', text: 'What type of pastry is traditionally used to make a croissant?', options: ['Shortcrust', 'Puff pastry', 'Filo pastry', 'Laminated dough'], correctIndex: 3 },
  { id: 'q035', category: 'food-drink', text: 'Which country is the origin of tequila?', options: ['Spain', 'Mexico', 'Brazil', 'Cuba'], correctIndex: 1 },
  { id: 'q036', category: 'food-drink', text: 'What is the main ingredient in guacamole?', options: ['Tomato', 'Avocado', 'Lime', 'Onion'], correctIndex: 1 },
  { id: 'q037', category: 'food-drink', text: 'Champagne must come from which region to bear that name?', options: ['Bordeaux', 'Provence', 'Champagne', 'Loire Valley'], correctIndex: 2 },
  { id: 'q038', category: 'food-drink', text: 'Which cheese is traditionally used in a classic Margherita pizza?', options: ['Cheddar', 'Mozzarella', 'Parmesan', 'Gouda'], correctIndex: 1 },
  { id: 'q039', category: 'food-drink', text: 'What is the main alcohol in a classic Old Fashioned cocktail?', options: ['Rum', 'Gin', 'Whiskey', 'Brandy'], correctIndex: 2 },
  { id: 'q040', category: 'food-drink', text: 'Sushi originated in which country?', options: ['China', 'Korea', 'Japan', 'Thailand'], correctIndex: 2 },

  // pop-culture (more)
  { id: 'q041', category: 'pop-culture', text: 'Which wizard owns the Marauder\'s Map in Harry Potter?', options: ['Harry Potter', 'Ron Weasley', 'Fred Weasley', 'Sirius Black'], correctIndex: 0 },
  { id: 'q042', category: 'pop-culture', text: 'Which actor played Iron Man in the Marvel Cinematic Universe?', options: ['Chris Evans', 'Robert Downey Jr.', 'Chris Hemsworth', 'Mark Ruffalo'], correctIndex: 1 },
  { id: 'q043', category: 'pop-culture', text: 'What is the name of the coffee shop in "Friends"?', options: ['Central Perk', 'Java Hut', 'The Grind', 'Perk Place'], correctIndex: 0 },
  { id: 'q044', category: 'pop-culture', text: 'Which band performed "Bohemian Rhapsody"?', options: ['The Rolling Stones', 'Led Zeppelin', 'Queen', 'Pink Floyd'], correctIndex: 2 },
  { id: 'q045', category: 'pop-culture', text: 'In "The Office" (US), who is the regional manager of Dunder Mifflin Scranton?', options: ['Jim Halpert', 'Michael Scott', 'Dwight Schrute', 'Andy Bernard'], correctIndex: 1 },
  { id: 'q046', category: 'pop-culture', text: 'Which artist is known for the song "Shape of You"?', options: ['Justin Bieber', 'Shawn Mendes', 'Ed Sheeran', 'Charlie Puth'], correctIndex: 2 },
  { id: 'q047', category: 'pop-culture', text: 'What is the highest-grossing animated film of all time?', options: ['Frozen II', 'The Lion King (2019)', 'Inside Out 2', 'Frozen'], correctIndex: 2 },
  { id: 'q048', category: 'pop-culture', text: 'Which TV series features the fictional kingdoms of Westeros and Essos?', options: ['The Witcher', 'Game of Thrones', 'House of the Dragon', 'Vikings'], correctIndex: 1 },
  { id: 'q049', category: 'pop-culture', text: 'Who is known as the "King of Pop"?', options: ['Prince', 'Elvis Presley', 'Michael Jackson', 'Justin Timberlake'], correctIndex: 2 },
  { id: 'q050', category: 'pop-culture', text: 'Which streaming platform released the series "The Crown"?', options: ['Netflix', 'Amazon Prime', 'Hulu', 'Apple TV+'], correctIndex: 0 },
  { id: 'q051', category: 'pop-culture', text: 'What is Spider-Man\'s real name?', options: ['Peter Parker', 'Tony Stark', 'Bruce Banner', 'Clark Kent'], correctIndex: 0 },
  { id: 'q052', category: 'pop-culture', text: 'Which reality show features contestants competing to become "the last one standing" for a cash prize, hosted by Jeff Probst?', options: ['Big Brother', 'Survivor', 'The Amazing Race', 'Naked and Afraid'], correctIndex: 1 },

  // history (more)
  { id: 'q053', category: 'history', text: 'Who was the British Prime Minister during most of World War II?', options: ['Neville Chamberlain', 'Winston Churchill', 'Clement Attlee', 'Anthony Eden'], correctIndex: 1 },
  { id: 'q054', category: 'history', text: 'The French Revolution began in which year?', options: ['1769', '1789', '1799', '1804'], correctIndex: 1 },
  { id: 'q055', category: 'history', text: 'Which ancient wonder of the world stood in Alexandria, Egypt?', options: ['The Hanging Gardens', 'The Great Lighthouse', 'The Colossus of Rhodes', 'The Temple of Artemis'], correctIndex: 1 },
  { id: 'q056', category: 'history', text: 'Who was the first man to walk on the Moon?', options: ['Buzz Aldrin', 'Yuri Gagarin', 'Neil Armstrong', 'John Glenn'], correctIndex: 2 },
  { id: 'q057', category: 'history', text: 'The Great Wall was built primarily to protect which country?', options: ['Japan', 'Mongolia', 'China', 'Korea'], correctIndex: 2 },
  { id: 'q058', category: 'history', text: 'In what year did India gain independence from British rule?', options: ['1945', '1947', '1950', '1952'], correctIndex: 1 },
  { id: 'q059', category: 'history', text: 'Who was the famous Macedonian king who conquered much of the known world by age 30?', options: ['Julius Caesar', 'Alexander the Great', 'Darius III', 'Hannibal'], correctIndex: 1 },
  { id: 'q060', category: 'history', text: 'Which wall divided a major German city from 1961 to 1989?', options: ['The Munich Wall', 'The Berlin Wall', 'The Bonn Wall', 'The Frankfurt Wall'], correctIndex: 1 },
  { id: 'q061', category: 'history', text: 'The Renaissance began in which country?', options: ['France', 'Spain', 'Italy', 'Germany'], correctIndex: 2 },
  { id: 'q062', category: 'history', text: 'Who wrote the American Declaration of Independence?', options: ['Benjamin Franklin', 'Thomas Jefferson', 'James Madison', 'John Adams'], correctIndex: 1 },
  { id: 'q063', category: 'history', text: 'Which empire was ruled by Genghis Khan?', options: ['Ottoman Empire', 'Mongol Empire', 'Persian Empire', 'Byzantine Empire'], correctIndex: 1 },
  { id: 'q064', category: 'history', text: 'The Cold War was primarily a standoff between the USA and which other nation?', options: ['China', 'Soviet Union', 'Germany', 'Cuba'], correctIndex: 1 },

  // sport (more)
  { id: 'q065', category: 'sport', text: 'In which sport is the term "love" used for a score of zero?', options: ['Squash', 'Badminton', 'Tennis', 'Table tennis'], correctIndex: 2 },
  { id: 'q066', category: 'sport', text: 'How many players are on a basketball team on the court at one time?', options: ['4', '5', '6', '7'], correctIndex: 1 },
  { id: 'q067', category: 'sport', text: 'Which country hosted the 2016 Summer Olympics?', options: ['China', 'United Kingdom', 'Brazil', 'Japan'], correctIndex: 2 },
  { id: 'q068', category: 'sport', text: 'In golf, what term describes a score of one under par on a hole?', options: ['Eagle', 'Bogey', 'Birdie', 'Albatross'], correctIndex: 2 },
  { id: 'q069', category: 'sport', text: 'Which sport is known as "the king of sports" worldwide?', options: ['Basketball', 'Football (soccer)', 'Cricket', 'Tennis'], correctIndex: 1 },
  { id: 'q070', category: 'sport', text: 'How many points is a try worth in rugby union?', options: ['3', '4', '5', '6'], correctIndex: 2 },
  { id: 'q071', category: 'sport', text: 'Which country is credited with inventing the sport of cricket?', options: ['Australia', 'India', 'England', 'South Africa'], correctIndex: 2 },
  { id: 'q072', category: 'sport', text: 'In Formula 1, what color flag signals the end of a race?', options: ['Yellow', 'Red', 'Checkered', 'Blue'], correctIndex: 2 },
  { id: 'q073', category: 'sport', text: 'How many holes are played in a standard round of golf?', options: ['9', '12', '18', '21'], correctIndex: 2 },
  { id: 'q074', category: 'sport', text: 'Which swimmer has won the most Olympic gold medals in history?', options: ['Mark Spitz', 'Ian Thorpe', 'Michael Phelps', 'Caeleb Dressel'], correctIndex: 2 },
  { id: 'q075', category: 'sport', text: 'In boxing, how many rounds are in a standard professional championship fight?', options: ['10', '12', '15', '8'], correctIndex: 1 },
  { id: 'q076', category: 'sport', text: 'Which country won the first ever FIFA World Cup in 1930?', options: ['Brazil', 'Argentina', 'Uruguay', 'Italy'], correctIndex: 2 },

  // science (more)
  { id: 'q077', category: 'science', text: 'What is the largest planet in our solar system?', options: ['Saturn', 'Neptune', 'Jupiter', 'Uranus'], correctIndex: 2 },
  { id: 'q078', category: 'science', text: 'What part of the plant conducts photosynthesis?', options: ['Roots', 'Stem', 'Leaves', 'Flowers'], correctIndex: 2 },
  { id: 'q079', category: 'science', text: 'What is the chemical formula for water?', options: ['CO2', 'H2O', 'O2', 'NaCl'], correctIndex: 1 },
  { id: 'q080', category: 'science', text: 'Which scientist proposed the theory of evolution by natural selection?', options: ['Gregor Mendel', 'Charles Darwin', 'Louis Pasteur', 'Carl Linnaeus'], correctIndex: 1 },
  { id: 'q081', category: 'science', text: 'What is the hardest natural substance on Earth?', options: ['Gold', 'Quartz', 'Diamond', 'Titanium'], correctIndex: 2 },
  { id: 'q082', category: 'science', text: 'How many planets are in our solar system?', options: ['7', '8', '9', '10'], correctIndex: 1 },
  { id: 'q083', category: 'science', text: 'What type of energy does a moving object have?', options: ['Potential energy', 'Kinetic energy', 'Thermal energy', 'Chemical energy'], correctIndex: 1 },
  { id: 'q084', category: 'science', text: 'What is the boiling point of water at sea level in Celsius?', options: ['90°C', '95°C', '100°C', '110°C'], correctIndex: 2 },
  { id: 'q085', category: 'science', text: 'Which gas makes up the majority of Earth\'s atmosphere?', options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'], correctIndex: 2 },
  { id: 'q086', category: 'science', text: 'What is the study of living organisms called?', options: ['Geology', 'Biology', 'Chemistry', 'Physics'], correctIndex: 1 },
  { id: 'q087', category: 'science', text: 'Which organ in the human body pumps blood?', options: ['Lungs', 'Liver', 'Heart', 'Kidney'], correctIndex: 2 },
  { id: 'q088', category: 'science', text: 'What force pulls objects toward the center of the Earth?', options: ['Magnetism', 'Friction', 'Gravity', 'Inertia'], correctIndex: 2 },

  // food-drink (more)
  { id: 'q089', category: 'food-drink', text: 'Which country is the largest producer of coffee in the world?', options: ['Colombia', 'Vietnam', 'Brazil', 'Ethiopia'], correctIndex: 2 },
  { id: 'q090', category: 'food-drink', text: 'What is the main ingredient in traditional hummus?', options: ['Lentils', 'Chickpeas', 'Black beans', 'Fava beans'], correctIndex: 1 },
  { id: 'q091', category: 'food-drink', text: 'Which spirit is distilled from agave?', options: ['Rum', 'Vodka', 'Tequila', 'Gin'], correctIndex: 2 },
  { id: 'q092', category: 'food-drink', text: 'What type of pasta is shaped like small rice grains?', options: ['Orzo', 'Penne', 'Fusilli', 'Farfalle'], correctIndex: 0 },
  { id: 'q093', category: 'food-drink', text: 'Which fruit is used to make traditional guacamole turn brown if exposed to air?', options: ['Lime', 'Avocado', 'Tomato', 'Onion'], correctIndex: 1 },
  { id: 'q094', category: 'food-drink', text: 'A "negroni" cocktail combines gin, Campari, and which other ingredient?', options: ['Sweet vermouth', 'Tonic water', 'Triple sec', 'Dry vermouth'], correctIndex: 0 },
  { id: 'q095', category: 'food-drink', text: 'Which country is famous for originating the dish paella?', options: ['Italy', 'Portugal', 'Spain', 'Greece'], correctIndex: 2 },
  { id: 'q096', category: 'food-drink', text: 'What is the primary grain used to brew most beer?', options: ['Wheat', 'Rice', 'Barley', 'Corn'], correctIndex: 2 },
  { id: 'q097', category: 'food-drink', text: 'Which cheese is traditionally used in a classic Greek salad?', options: ['Mozzarella', 'Feta', 'Halloumi', 'Ricotta'], correctIndex: 1 },
  { id: 'q098', category: 'food-drink', text: 'What is the key spirit in a classic daiquiri?', options: ['Vodka', 'Gin', 'Rum', 'Whiskey'], correctIndex: 2 },
  { id: 'q099', category: 'food-drink', text: 'Which country is credited with inventing pizza in its modern form?', options: ['Greece', 'Italy', 'France', 'Turkey'], correctIndex: 1 },
  { id: 'q100', category: 'food-drink', text: 'What is the main ingredient in traditional miso soup?', options: ['Soybean paste', 'Seaweed only', 'Rice vinegar', 'Coconut milk'], correctIndex: 0 },
]
