// difficulty: 'easy' | 'medium' | 'hard' | 'expert' — exactly 10 of each per
// category (40/category), so a player's 4 questions can be dealt one per
// tier and get progressively harder as the turn goes on.
export const QUESTIONS = [
  // pop-culture
  { id: 'q001', category: 'pop-culture', difficulty: 'easy', text: 'Which streaming service produced "Stranger Things"?', options: ['Hulu', 'Netflix', 'Disney+', 'Amazon Prime'], correctIndex: 1 },
  { id: 'q002', category: 'pop-culture', difficulty: 'easy', text: 'Who played the Joker in "The Dark Knight"?', options: ['Joaquin Phoenix', 'Jared Leto', 'Heath Ledger', 'Jack Nicholson'], correctIndex: 2 },
  { id: 'q003', category: 'pop-culture', difficulty: 'hard', text: 'What is the best-selling music artist of all time?', options: ['Madonna', 'The Beatles', 'Elvis Presley', 'Michael Jackson'], correctIndex: 1 },
  { id: 'q004', category: 'pop-culture', difficulty: 'easy', text: 'Which fictional city does Batman protect?', options: ['Metropolis', 'Star City', 'Gotham City', 'Central City'], correctIndex: 2 },
  { id: 'q005', category: 'pop-culture', difficulty: 'easy', text: 'Which artist released the album "Lemonade"?', options: ['Rihanna', 'Beyoncé', 'Adele', 'Nicki Minaj'], correctIndex: 1 },
  { id: 'q006', category: 'pop-culture', difficulty: 'expert', text: 'What is the highest-grossing film of all time (unadjusted)?', options: ['Titanic', 'Avengers: Endgame', 'Avatar', 'Star Wars: The Force Awakens'], correctIndex: 2 },
  { id: 'q007', category: 'pop-culture', difficulty: 'expert', text: 'In "Friends", what is the name of Ross and Monica\'s pet monkey?', options: ['Marcel', 'George', 'Chandler', 'Gunther'], correctIndex: 0 },
  { id: 'q008', category: 'pop-culture', difficulty: 'medium', text: 'Which singer is known as the "Queen of Pop"?', options: ['Lady Gaga', 'Britney Spears', 'Madonna', 'Mariah Carey'], correctIndex: 2 },
  { id: 'q041', category: 'pop-culture', difficulty: 'expert', text: 'Which wizard owns the Marauder\'s Map in Harry Potter?', options: ['Harry Potter', 'Ron Weasley', 'Fred Weasley', 'Sirius Black'], correctIndex: 0 },
  { id: 'q042', category: 'pop-culture', difficulty: 'medium', text: 'Which actor played Iron Man in the Marvel Cinematic Universe?', options: ['Chris Evans', 'Robert Downey Jr.', 'Chris Hemsworth', 'Mark Ruffalo'], correctIndex: 1 },
  { id: 'q043', category: 'pop-culture', difficulty: 'hard', text: 'What is the name of the coffee shop in "Friends"?', options: ['Central Perk', 'Java Hut', 'The Grind', 'Perk Place'], correctIndex: 0 },
  { id: 'q044', category: 'pop-culture', difficulty: 'medium', text: 'Which band performed "Bohemian Rhapsody"?', options: ['The Rolling Stones', 'Led Zeppelin', 'Queen', 'Pink Floyd'], correctIndex: 2 },
  { id: 'q045', category: 'pop-culture', difficulty: 'medium', text: 'In "The Office" (US), who is the regional manager of Dunder Mifflin Scranton?', options: ['Jim Halpert', 'Michael Scott', 'Dwight Schrute', 'Andy Bernard'], correctIndex: 1 },
  { id: 'q046', category: 'pop-culture', difficulty: 'hard', text: 'Which artist is known for the song "Shape of You"?', options: ['Justin Bieber', 'Shawn Mendes', 'Ed Sheeran', 'Charlie Puth'], correctIndex: 2 },
  { id: 'q047', category: 'pop-culture', difficulty: 'expert', text: 'What is the highest-grossing animated film of all time?', options: ['Frozen II', 'The Lion King (2019)', 'Inside Out 2', 'Frozen'], correctIndex: 2 },
  { id: 'q048', category: 'pop-culture', difficulty: 'hard', text: 'Which TV series features the fictional kingdoms of Westeros and Essos?', options: ['The Witcher', 'Game of Thrones', 'House of the Dragon', 'Vikings'], correctIndex: 1 },
  { id: 'q049', category: 'pop-culture', difficulty: 'medium', text: 'Who is known as the "King of Pop"?', options: ['Prince', 'Elvis Presley', 'Michael Jackson', 'Justin Timberlake'], correctIndex: 2 },
  { id: 'q050', category: 'pop-culture', difficulty: 'hard', text: 'Which streaming platform released the series "The Crown"?', options: ['Netflix', 'Amazon Prime', 'Hulu', 'Apple TV+'], correctIndex: 0 },
  { id: 'q051', category: 'pop-culture', difficulty: 'easy', text: 'What is Spider-Man\'s real name?', options: ['Peter Parker', 'Tony Stark', 'Bruce Banner', 'Clark Kent'], correctIndex: 0 },
  { id: 'q052', category: 'pop-culture', difficulty: 'expert', text: 'Which reality show features contestants competing to become "the last one standing" for a cash prize, hosted by Jeff Probst?', options: ['Big Brother', 'Survivor', 'The Amazing Race', 'Naked and Afraid'], correctIndex: 1 },
  { id: 'q101', category: 'pop-culture', difficulty: 'easy', text: 'Which animated film features a clownfish named Marlin searching for his son?', options: ['Shark Tale', 'Finding Nemo', 'Happy Feet', 'Finding Dory'], correctIndex: 1 },
  { id: 'q102', category: 'pop-culture', difficulty: 'easy', text: 'Who is the lead singer of the band Coldplay?', options: ['Liam Gallagher', 'Bono', 'Chris Martin', 'Thom Yorke'], correctIndex: 2 },
  { id: 'q103', category: 'pop-culture', difficulty: 'easy', text: 'Which short-form video app was popular for looping videos before being shut down in 2017?', options: ['TikTok', 'Vine', 'Snapchat', 'Periscope'], correctIndex: 1 },
  { id: 'q104', category: 'pop-culture', difficulty: 'easy', text: 'In Disney\'s "Frozen", what is the name of the talking snowman?', options: ['Sven', 'Kristoff', 'Olaf', 'Hans'], correctIndex: 2 },
  { id: 'q105', category: 'pop-culture', difficulty: 'easy', text: 'Which superhero is known as the "Man of Steel"?', options: ['Batman', 'Superman', 'Thor', 'Captain America'], correctIndex: 1 },
  { id: 'q106', category: 'pop-culture', difficulty: 'medium', text: 'Which Netflix series is set in the fictional town of Hawkins, Indiana?', options: ['Dark', 'Stranger Things', 'The OA', 'Ozark'], correctIndex: 1 },
  { id: 'q107', category: 'pop-culture', difficulty: 'medium', text: 'Who directed the 1975 film "Jaws"?', options: ['George Lucas', 'Steven Spielberg', 'Martin Scorsese', 'Francis Ford Coppola'], correctIndex: 1 },
  { id: 'q108', category: 'pop-culture', difficulty: 'medium', text: 'Which British musician is known for the hit "Rocket Man"?', options: ['David Bowie', 'Elton John', 'Rod Stewart', 'Phil Collins'], correctIndex: 1 },
  { id: 'q109', category: 'pop-culture', difficulty: 'medium', text: 'What is the name of Harry Potter\'s pet owl?', options: ['Errol', 'Hedwig', 'Pigwidgeon', 'Scabbers'], correctIndex: 1 },
  { id: 'q110', category: 'pop-culture', difficulty: 'medium', text: 'Which actress played Hermione Granger in the Harry Potter film series?', options: ['Bonnie Wright', 'Emma Watson', 'Evanna Lynch', 'Katie Leung'], correctIndex: 1 },
  { id: 'q111', category: 'pop-culture', difficulty: 'hard', text: 'Which musician is nicknamed "The Boss"?', options: ['Bob Dylan', 'Bruce Springsteen', 'Billy Joel', 'Tom Petty'], correctIndex: 1 },
  { id: 'q112', category: 'pop-culture', difficulty: 'hard', text: 'In "Breaking Bad", what alias does Walter White use in the drug trade?', options: ['Scarface', 'Heisenberg', 'El Jefe', 'The Cook'], correctIndex: 1 },
  { id: 'q113', category: 'pop-culture', difficulty: 'hard', text: 'Which Beatles album features the iconic cover of the band crossing a London street?', options: ['Let It Be', 'Revolver', 'Abbey Road', 'The White Album'], correctIndex: 2 },
  { id: 'q114', category: 'pop-culture', difficulty: 'hard', text: 'Who composed the iconic film scores for "Star Wars" and "Jaws"?', options: ['Hans Zimmer', 'John Williams', 'Danny Elfman', 'James Horner'], correctIndex: 1 },
  { id: 'q115', category: 'pop-culture', difficulty: 'hard', text: 'Which actor has portrayed James Bond in the most films?', options: ['Sean Connery', 'Roger Moore', 'Daniel Craig', 'Pierce Brosnan'], correctIndex: 1 },
  { id: 'q116', category: 'pop-culture', difficulty: 'expert', text: 'What is the name of the fictional African nation in "Black Panther"?', options: ['Zamunda', 'Wakanda', 'Genovia', 'Latveria'], correctIndex: 1 },
  { id: 'q117', category: 'pop-culture', difficulty: 'expert', text: 'Which director made "Pulp Fiction" and "Reservoir Dogs"?', options: ['Martin Scorsese', 'Quentin Tarantino', 'David Fincher', 'Guy Ritchie'], correctIndex: 1 },
  { id: 'q118', category: 'pop-culture', difficulty: 'expert', text: 'In "The Lord of the Rings", what is the name of Frodo\'s sword?', options: ['Glamdring', 'Sting', 'Anduril', 'Orcrist'], correctIndex: 1 },
  { id: 'q119', category: 'pop-culture', difficulty: 'expert', text: '"Stefani Joanne Angelina Germanotta" is the real name of which pop star?', options: ['Katy Perry', 'Lady Gaga', 'Madonna', 'Pink'], correctIndex: 1 },
  { id: 'q120', category: 'pop-culture', difficulty: 'expert', text: 'Which 1994 film won the Academy Award for Best Picture, beating "Pulp Fiction" and "The Shawshank Redemption"?', options: ['Forrest Gump', 'Braveheart', 'Apollo 13', 'The Fugitive'], correctIndex: 0 },

  // history
  { id: 'q009', category: 'history', difficulty: 'medium', text: 'In what year did the Berlin Wall fall?', options: ['1987', '1991', '1989', '1993'], correctIndex: 2 },
  { id: 'q010', category: 'history', difficulty: 'easy', text: 'Who was the first President of the United States?', options: ['Thomas Jefferson', 'John Adams', 'George Washington', 'Benjamin Franklin'], correctIndex: 2 },
  { id: 'q011', category: 'history', difficulty: 'easy', text: 'Which empire built the Colosseum?', options: ['Greek', 'Roman', 'Ottoman', 'Persian'], correctIndex: 1 },
  { id: 'q012', category: 'history', difficulty: 'easy', text: 'In what year did World War II end?', options: ['1943', '1944', '1945', '1946'], correctIndex: 2 },
  { id: 'q013', category: 'history', difficulty: 'medium', text: 'Who was the famous queen of ancient Egypt who allied with Mark Antony?', options: ['Nefertiti', 'Hatshepsut', 'Cleopatra', 'Ankhesenamun'], correctIndex: 2 },
  { id: 'q014', category: 'history', difficulty: 'easy', text: 'Which country gifted the Statue of Liberty to the USA?', options: ['United Kingdom', 'Spain', 'France', 'Italy'], correctIndex: 2 },
  { id: 'q015', category: 'history', difficulty: 'medium', text: 'The Titanic sank in which year?', options: ['1905', '1912', '1918', '1923'], correctIndex: 1 },
  { id: 'q016', category: 'history', difficulty: 'expert', text: 'Who was the leader of the Soviet Union during the Cuban Missile Crisis?', options: ['Stalin', 'Khrushchev', 'Lenin', 'Gorbachev'], correctIndex: 1 },
  { id: 'q053', category: 'history', difficulty: 'medium', text: 'Who was the British Prime Minister during most of World War II?', options: ['Neville Chamberlain', 'Winston Churchill', 'Clement Attlee', 'Anthony Eden'], correctIndex: 1 },
  { id: 'q054', category: 'history', difficulty: 'hard', text: 'The French Revolution began in which year?', options: ['1769', '1789', '1799', '1804'], correctIndex: 1 },
  { id: 'q055', category: 'history', difficulty: 'expert', text: 'Which ancient wonder of the world stood in Alexandria, Egypt?', options: ['The Hanging Gardens', 'The Great Lighthouse', 'The Colossus of Rhodes', 'The Temple of Artemis'], correctIndex: 1 },
  { id: 'q056', category: 'history', difficulty: 'easy', text: 'Who was the first man to walk on the Moon?', options: ['Buzz Aldrin', 'Yuri Gagarin', 'Neil Armstrong', 'John Glenn'], correctIndex: 2 },
  { id: 'q057', category: 'history', difficulty: 'hard', text: 'The Great Wall was built primarily to protect which country?', options: ['Japan', 'Mongolia', 'China', 'Korea'], correctIndex: 2 },
  { id: 'q058', category: 'history', difficulty: 'hard', text: 'In what year did India gain independence from British rule?', options: ['1945', '1947', '1950', '1952'], correctIndex: 1 },
  { id: 'q059', category: 'history', difficulty: 'expert', text: 'Who was the famous Macedonian king who conquered much of the known world by age 30?', options: ['Julius Caesar', 'Alexander the Great', 'Darius III', 'Hannibal'], correctIndex: 1 },
  { id: 'q060', category: 'history', difficulty: 'medium', text: 'Which wall divided a major German city from 1961 to 1989?', options: ['The Munich Wall', 'The Berlin Wall', 'The Bonn Wall', 'The Frankfurt Wall'], correctIndex: 1 },
  { id: 'q061', category: 'history', difficulty: 'hard', text: 'The Renaissance began in which country?', options: ['France', 'Spain', 'Italy', 'Germany'], correctIndex: 2 },
  { id: 'q062', category: 'history', difficulty: 'expert', text: 'Who wrote the American Declaration of Independence?', options: ['Benjamin Franklin', 'Thomas Jefferson', 'James Madison', 'John Adams'], correctIndex: 1 },
  { id: 'q063', category: 'history', difficulty: 'expert', text: 'Which empire was ruled by Genghis Khan?', options: ['Ottoman Empire', 'Mongol Empire', 'Persian Empire', 'Byzantine Empire'], correctIndex: 1 },
  { id: 'q064', category: 'history', difficulty: 'hard', text: 'The Cold War was primarily a standoff between the USA and which other nation?', options: ['China', 'Soviet Union', 'Germany', 'Cuba'], correctIndex: 1 },
  { id: 'q121', category: 'history', difficulty: 'easy', text: 'Which ancient civilization built the pyramids of Giza?', options: ['Mesopotamians', 'Egyptians', 'Romans', 'Greeks'], correctIndex: 1 },
  { id: 'q122', category: 'history', difficulty: 'easy', text: 'Who was the first Emperor of Rome?', options: ['Julius Caesar', 'Augustus', 'Nero', 'Caligula'], correctIndex: 1 },
  { id: 'q123', category: 'history', difficulty: 'easy', text: 'In what year did the United States declare independence?', options: ['1774', '1776', '1781', '1789'], correctIndex: 1 },
  { id: 'q124', category: 'history', difficulty: 'easy', text: 'Which war was fought between the Northern and Southern United States from 1861 to 1865?', options: ['The Revolutionary War', 'The American Civil War', 'World War I', 'The War of 1812'], correctIndex: 1 },
  { id: 'q125', category: 'history', difficulty: 'easy', text: 'Who was the British monarch for most of the 19th century\'s Victorian era?', options: ['Queen Elizabeth I', 'Queen Victoria', 'Queen Anne', 'Queen Mary I'], correctIndex: 1 },
  { id: 'q126', category: 'history', difficulty: 'medium', text: 'Germany was unified into a single empire in 1871 under whose leadership?', options: ['Adolf Hitler', 'Otto von Bismarck', 'Kaiser Wilhelm I', 'Frederick the Great'], correctIndex: 1 },
  { id: 'q127', category: 'history', difficulty: 'medium', text: 'The Magna Carta, limiting the power of the English king, was signed in which year?', options: ['1066', '1215', '1348', '1492'], correctIndex: 1 },
  { id: 'q128', category: 'history', difficulty: 'medium', text: 'Which Egyptian pharaoh\'s nearly intact tomb was discovered by Howard Carter in 1922?', options: ['Ramesses II', 'Akhenaten', 'Tutankhamun', 'Khufu'], correctIndex: 2 },
  { id: 'q129', category: 'history', difficulty: 'medium', text: 'Which war officially ended with the Treaty of Versailles in 1919?', options: ['World War II', 'World War I', 'The Franco-Prussian War', 'The Crimean War'], correctIndex: 1 },
  { id: 'q130', category: 'history', difficulty: 'medium', text: 'Who was the first woman to fly solo across the Atlantic Ocean?', options: ['Bessie Coleman', 'Amelia Earhart', 'Harriet Quimby', 'Jacqueline Cochran'], correctIndex: 1 },
  { id: 'q131', category: 'history', difficulty: 'hard', text: 'The Hundred Years\' War was fought primarily between which two countries?', options: ['Spain and Portugal', 'England and France', 'Germany and France', 'England and Scotland'], correctIndex: 1 },
  { id: 'q132', category: 'history', difficulty: 'hard', text: 'Who was the last Tsar of Russia, deposed during the 1917 Revolution?', options: ['Alexander III', 'Nicholas II', 'Peter the Great', 'Ivan the Terrible'], correctIndex: 1 },
  { id: 'q133', category: 'history', difficulty: 'hard', text: 'The Battle of Hastings, which led to the Norman conquest of England, took place in which year?', options: ['1066', '1215', '1314', '998'], correctIndex: 0 },
  { id: 'q134', category: 'history', difficulty: 'hard', text: 'The Ottoman Empire reached its peak under which sultan?', options: ['Suleiman the Magnificent', 'Mehmed II', 'Selim I', 'Osman I'], correctIndex: 0 },
  { id: 'q135', category: 'history', difficulty: 'hard', text: 'In what year was the Treaty of Versailles signed, formally ending World War I?', options: ['1917', '1918', '1919', '1920'], correctIndex: 2 },
  { id: 'q136', category: 'history', difficulty: 'expert', text: 'Who was the Byzantine Emperor when Constantinople fell to the Ottomans in 1453?', options: ['Justinian I', 'Constantine XI', 'Constantine the Great', 'Basil II'], correctIndex: 1 },
  { id: 'q137', category: 'history', difficulty: 'expert', text: 'Which English queen earned the nickname "Bloody Mary" for her persecution of Protestants?', options: ['Mary, Queen of Scots', 'Mary I', 'Mary II', 'Lady Jane Grey'], correctIndex: 1 },
  { id: 'q138', category: 'history', difficulty: 'expert', text: 'The "Defenestration of Prague" in 1618 helped trigger which major European war?', options: ['The Thirty Years\' War', 'The Seven Years\' War', 'The War of Spanish Succession', 'The Napoleonic Wars'], correctIndex: 0 },
  { id: 'q139', category: 'history', difficulty: 'expert', text: 'Which Carthaginian general famously crossed the Alps with war elephants to attack Rome?', options: ['Hamilcar Barca', 'Hannibal', 'Scipio Africanus', 'Hasdrubal'], correctIndex: 1 },
  { id: 'q140', category: 'history', difficulty: 'expert', text: 'Which 1648 peace treaty ended the Thirty Years\' War?', options: ['Treaty of Tordesillas', 'Peace of Westphalia', 'Treaty of Utrecht', 'Congress of Vienna'], correctIndex: 1 },

  // sport
  { id: 'q017', category: 'sport', difficulty: 'easy', text: 'How many players are on a standard football (soccer) team on the pitch?', options: ['9', '10', '11', '12'], correctIndex: 2 },
  { id: 'q018', category: 'sport', difficulty: 'easy', text: 'In which sport would you perform a "slam dunk"?', options: ['Volleyball', 'Basketball', 'Tennis', 'Handball'], correctIndex: 1 },
  { id: 'q019', category: 'sport', difficulty: 'easy', text: 'How often are the Summer Olympic Games held?', options: ['Every 2 years', 'Every 3 years', 'Every 4 years', 'Every 5 years'], correctIndex: 2 },
  { id: 'q020', category: 'sport', difficulty: 'hard', text: 'Which country has won the most FIFA World Cups?', options: ['Germany', 'Argentina', 'Italy', 'Brazil'], correctIndex: 3 },
  { id: 'q021', category: 'sport', difficulty: 'medium', text: 'In tennis, what is a score of zero called?', options: ['Nil', 'Love', 'Zero', 'Nought'], correctIndex: 1 },
  { id: 'q022', category: 'sport', difficulty: 'easy', text: 'How many rings are on the Olympic flag?', options: ['4', '5', '6', '7'], correctIndex: 1 },
  { id: 'q023', category: 'sport', difficulty: 'medium', text: 'Which boxer was known as "The Greatest"?', options: ['Mike Tyson', 'Joe Frazier', 'Muhammad Ali', 'George Foreman'], correctIndex: 2 },
  { id: 'q024', category: 'sport', difficulty: 'expert', text: 'What is the maximum score possible with three darts in a single visit?', options: ['170', '180', '160', '150'], correctIndex: 1 },
  { id: 'q065', category: 'sport', difficulty: 'hard', text: 'In which sport is the term "love" used for a score of zero?', options: ['Squash', 'Badminton', 'Tennis', 'Table tennis'], correctIndex: 2 },
  { id: 'q066', category: 'sport', difficulty: 'medium', text: 'How many players are on a basketball team on the court at one time?', options: ['4', '5', '6', '7'], correctIndex: 1 },
  { id: 'q067', category: 'sport', difficulty: 'hard', text: 'Which country hosted the 2016 Summer Olympics?', options: ['China', 'United Kingdom', 'Brazil', 'Japan'], correctIndex: 2 },
  { id: 'q068', category: 'sport', difficulty: 'hard', text: 'In golf, what term describes a score of one under par on a hole?', options: ['Eagle', 'Bogey', 'Birdie', 'Albatross'], correctIndex: 2 },
  { id: 'q069', category: 'sport', difficulty: 'medium', text: 'Which sport is known as "the king of sports" worldwide?', options: ['Basketball', 'Football (soccer)', 'Cricket', 'Tennis'], correctIndex: 1 },
  { id: 'q070', category: 'sport', difficulty: 'expert', text: 'How many points is a try worth in rugby union?', options: ['3', '4', '5', '6'], correctIndex: 2 },
  { id: 'q071', category: 'sport', difficulty: 'expert', text: 'Which country is credited with inventing the sport of cricket?', options: ['Australia', 'India', 'England', 'South Africa'], correctIndex: 2 },
  { id: 'q072', category: 'sport', difficulty: 'medium', text: 'In Formula 1, what color flag signals the end of a race?', options: ['Yellow', 'Red', 'Checkered', 'Blue'], correctIndex: 2 },
  { id: 'q073', category: 'sport', difficulty: 'easy', text: 'How many holes are played in a standard round of golf?', options: ['9', '12', '18', '21'], correctIndex: 2 },
  { id: 'q074', category: 'sport', difficulty: 'hard', text: 'Which swimmer has won the most Olympic gold medals in history?', options: ['Mark Spitz', 'Ian Thorpe', 'Michael Phelps', 'Caeleb Dressel'], correctIndex: 2 },
  { id: 'q075', category: 'sport', difficulty: 'expert', text: 'In boxing, how many rounds are in a standard professional championship fight?', options: ['10', '12', '15', '8'], correctIndex: 1 },
  { id: 'q076', category: 'sport', difficulty: 'expert', text: 'Which country won the first ever FIFA World Cup in 1930?', options: ['Brazil', 'Argentina', 'Uruguay', 'Italy'], correctIndex: 2 },
  { id: 'q141', category: 'sport', difficulty: 'easy', text: 'How many players make up a rugby union team on the field at one time?', options: ['11', '13', '15', '7'], correctIndex: 2 },
  { id: 'q142', category: 'sport', difficulty: 'easy', text: 'In which sport do players use a shuttlecock?', options: ['Tennis', 'Squash', 'Badminton', 'Table tennis'], correctIndex: 2 },
  { id: 'q143', category: 'sport', difficulty: 'easy', text: 'How many periods are in a standard ice hockey game?', options: ['2', '3', '4', '5'], correctIndex: 1 },
  { id: 'q144', category: 'sport', difficulty: 'easy', text: 'Which Grand Slam tennis tournament is played on grass courts in London?', options: ['French Open', 'US Open', 'Wimbledon', 'Australian Open'], correctIndex: 2 },
  { id: 'q145', category: 'sport', difficulty: 'easy', text: 'In baseball, how many strikes result in a batter being out?', options: ['2', '3', '4', '5'], correctIndex: 1 },
  { id: 'q146', category: 'sport', difficulty: 'medium', text: 'Which country has won the most Cricket World Cup titles?', options: ['India', 'England', 'Australia', 'West Indies'], correctIndex: 2 },
  { id: 'q147', category: 'sport', difficulty: 'medium', text: 'In which sport would a player perform a "header"?', options: ['Volleyball', 'Football (soccer)', 'Basketball', 'Rugby'], correctIndex: 1 },
  { id: 'q148', category: 'sport', difficulty: 'medium', text: 'In Australian rules football, how many points is a goal (through the main posts) worth?', options: ['1', '3', '6', '8'], correctIndex: 2 },
  { id: 'q149', category: 'sport', difficulty: 'medium', text: 'Which Grand Slam tennis tournament is played on clay courts?', options: ['Wimbledon', 'US Open', 'French Open', 'Australian Open'], correctIndex: 2 },
  { id: 'q150', category: 'sport', difficulty: 'medium', text: 'In American football, how many points is a touchdown worth (before extra point attempts)?', options: ['3', '6', '7', '9'], correctIndex: 1 },
  { id: 'q151', category: 'sport', difficulty: 'hard', text: 'Which country won the UEFA European Championship (Euro) in 2016?', options: ['France', 'Germany', 'Portugal', 'Spain'], correctIndex: 2 },
  { id: 'q152', category: 'sport', difficulty: 'hard', text: 'Who holds the record for the most goals scored across all FIFA World Cup tournaments?', options: ['Ronaldo', 'Miroslav Klose', 'Pele', 'Just Fontaine'], correctIndex: 1 },
  { id: 'q153', category: 'sport', difficulty: 'hard', text: 'In what year were the first modern Olympic Games held in Athens?', options: ['1892', '1896', '1900', '1904'], correctIndex: 1 },
  { id: 'q154', category: 'sport', difficulty: 'hard', text: 'Which annual horse race is nicknamed "the most exciting two minutes in sports"?', options: ['Royal Ascot', 'The Kentucky Derby', 'The Grand National', 'The Melbourne Cup'], correctIndex: 1 },
  { id: 'q155', category: 'sport', difficulty: 'hard', text: 'Which country has won the most Rugby World Cup titles?', options: ['South Africa', 'Australia', 'New Zealand', 'England'], correctIndex: 2 },
  { id: 'q156', category: 'sport', difficulty: 'expert', text: 'Who was the first gymnast to be awarded a perfect score of 10 at the Olympics?', options: ['Simone Biles', 'Olga Korbut', 'Nadia Comăneci', 'Mary Lou Retton'], correctIndex: 2 },
  { id: 'q157', category: 'sport', difficulty: 'expert', text: 'Which team won the first ever Cricket World Cup in 1975?', options: ['Australia', 'England', 'West Indies', 'India'], correctIndex: 2 },
  { id: 'q158', category: 'sport', difficulty: 'expert', text: 'In snooker, what is the maximum possible break a player can score in a single visit?', options: ['147', '155', '120', '180'], correctIndex: 0 },
  { id: 'q159', category: 'sport', difficulty: 'expert', text: 'Who became the youngest undisputed World Chess Champion in history at age 22?', options: ['Bobby Fischer', 'Garry Kasparov', 'Magnus Carlsen', 'Anatoly Karpov'], correctIndex: 1 },
  { id: 'q160', category: 'sport', difficulty: 'expert', text: 'Which heavyweight boxer retired with a perfect undefeated professional record of 49-0?', options: ['Joe Louis', 'Rocky Marciano', 'Muhammad Ali', 'Floyd Patterson'], correctIndex: 1 },

  // science
  { id: 'q025', category: 'science', difficulty: 'medium', text: 'What is the chemical symbol for gold?', options: ['Go', 'Gd', 'Au', 'Ag'], correctIndex: 2 },
  { id: 'q026', category: 'science', difficulty: 'easy', text: 'What planet is known as the Red Planet?', options: ['Venus', 'Jupiter', 'Saturn', 'Mars'], correctIndex: 3 },
  { id: 'q027', category: 'science', difficulty: 'hard', text: 'What gas do plants primarily absorb from the atmosphere?', options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'], correctIndex: 2 },
  { id: 'q028', category: 'science', difficulty: 'expert', text: 'How many bones are in the adult human body?', options: ['186', '206', '226', '246'], correctIndex: 1 },
  { id: 'q029', category: 'science', difficulty: 'expert', text: 'What is the speed of light approximately?', options: ['300,000 km/s', '150,000 km/s', '3,000 km/s', '30,000 km/s'], correctIndex: 0 },
  { id: 'q030', category: 'science', difficulty: 'hard', text: 'Who developed the theory of general relativity?', options: ['Isaac Newton', 'Niels Bohr', 'Albert Einstein', 'Stephen Hawking'], correctIndex: 2 },
  { id: 'q031', category: 'science', difficulty: 'expert', text: 'What is the powerhouse of the cell?', options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Golgi apparatus'], correctIndex: 2 },
  { id: 'q032', category: 'science', difficulty: 'medium', text: 'Which element has the atomic number 1?', options: ['Helium', 'Hydrogen', 'Oxygen', 'Carbon'], correctIndex: 1 },
  { id: 'q077', category: 'science', difficulty: 'medium', text: 'What is the largest planet in our solar system?', options: ['Saturn', 'Neptune', 'Jupiter', 'Uranus'], correctIndex: 2 },
  { id: 'q078', category: 'science', difficulty: 'easy', text: 'What part of the plant conducts photosynthesis?', options: ['Roots', 'Stem', 'Leaves', 'Flowers'], correctIndex: 2 },
  { id: 'q079', category: 'science', difficulty: 'easy', text: 'What is the chemical formula for water?', options: ['CO2', 'H2O', 'O2', 'NaCl'], correctIndex: 1 },
  { id: 'q080', category: 'science', difficulty: 'hard', text: 'Which scientist proposed the theory of evolution by natural selection?', options: ['Gregor Mendel', 'Charles Darwin', 'Louis Pasteur', 'Carl Linnaeus'], correctIndex: 1 },
  { id: 'q081', category: 'science', difficulty: 'medium', text: 'What is the hardest natural substance on Earth?', options: ['Gold', 'Quartz', 'Diamond', 'Titanium'], correctIndex: 2 },
  { id: 'q082', category: 'science', difficulty: 'hard', text: 'How many planets are in our solar system?', options: ['7', '8', '9', '10'], correctIndex: 1 },
  { id: 'q083', category: 'science', difficulty: 'expert', text: 'What type of energy does a moving object have?', options: ['Potential energy', 'Kinetic energy', 'Thermal energy', 'Chemical energy'], correctIndex: 1 },
  { id: 'q084', category: 'science', difficulty: 'hard', text: 'What is the boiling point of water at sea level in Celsius?', options: ['90°C', '95°C', '100°C', '110°C'], correctIndex: 2 },
  { id: 'q085', category: 'science', difficulty: 'expert', text: 'Which gas makes up the majority of Earth\'s atmosphere?', options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'], correctIndex: 2 },
  { id: 'q086', category: 'science', difficulty: 'medium', text: 'What is the study of living organisms called?', options: ['Geology', 'Biology', 'Chemistry', 'Physics'], correctIndex: 1 },
  { id: 'q087', category: 'science', difficulty: 'easy', text: 'Which organ in the human body pumps blood?', options: ['Lungs', 'Liver', 'Heart', 'Kidney'], correctIndex: 2 },
  { id: 'q088', category: 'science', difficulty: 'easy', text: 'What force pulls objects toward the center of the Earth?', options: ['Magnetism', 'Friction', 'Gravity', 'Inertia'], correctIndex: 2 },
  { id: 'q161', category: 'science', difficulty: 'easy', text: 'Which planet in our solar system is closest to the Sun?', options: ['Venus', 'Mercury', 'Mars', 'Earth'], correctIndex: 1 },
  { id: 'q162', category: 'science', difficulty: 'easy', text: 'Which gas do humans primarily need to breathe in order to survive?', options: ['Carbon dioxide', 'Nitrogen', 'Oxygen', 'Helium'], correctIndex: 2 },
  { id: 'q163', category: 'science', difficulty: 'easy', text: 'How many legs does a typical spider have?', options: ['6', '8', '10', '12'], correctIndex: 1 },
  { id: 'q164', category: 'science', difficulty: 'easy', text: 'What is the freezing point of water in degrees Celsius?', options: ['-10°C', '0°C', '10°C', '32°C'], correctIndex: 1 },
  { id: 'q165', category: 'science', difficulty: 'easy', text: 'Which planet is best known for its prominent ring system?', options: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'], correctIndex: 1 },
  { id: 'q166', category: 'science', difficulty: 'medium', text: 'What is the chemical symbol for sodium?', options: ['So', 'Sd', 'Na', 'S'], correctIndex: 2 },
  { id: 'q167', category: 'science', difficulty: 'medium', text: 'Which blood type is known as the "universal donor"?', options: ['AB positive', 'O negative', 'A positive', 'B negative'], correctIndex: 1 },
  { id: 'q168', category: 'science', difficulty: 'medium', text: 'Which organ in the human body primarily produces insulin?', options: ['Liver', 'Kidney', 'Pancreas', 'Spleen'], correctIndex: 2 },
  { id: 'q169', category: 'science', difficulty: 'medium', text: 'What is the smallest structural and functional unit of life called?', options: ['Atom', 'Molecule', 'Cell', 'Organelle'], correctIndex: 2 },
  { id: 'q170', category: 'science', difficulty: 'medium', text: 'What is the process by which plants convert sunlight into chemical energy called?', options: ['Respiration', 'Photosynthesis', 'Transpiration', 'Fermentation'], correctIndex: 1 },
  { id: 'q171', category: 'science', difficulty: 'hard', text: 'What is the chemical symbol for potassium?', options: ['Po', 'Pt', 'P', 'K'], correctIndex: 3 },
  { id: 'q172', category: 'science', difficulty: 'hard', text: 'Which scientist is credited with discovering penicillin in 1928?', options: ['Louis Pasteur', 'Alexander Fleming', 'Robert Koch', 'Joseph Lister'], correctIndex: 1 },
  { id: 'q173', category: 'science', difficulty: 'hard', text: 'What is the most abundant element in the universe by mass?', options: ['Helium', 'Oxygen', 'Hydrogen', 'Carbon'], correctIndex: 2 },
  { id: 'q174', category: 'science', difficulty: 'hard', text: 'Which part of the human eye controls the amount of light that enters?', options: ['Cornea', 'Retina', 'Iris', 'Lens'], correctIndex: 2 },
  { id: 'q175', category: 'science', difficulty: 'hard', text: 'What term describes an animal that is primarily active at night?', options: ['Diurnal', 'Nocturnal', 'Crepuscular', 'Dormant'], correctIndex: 1 },
  { id: 'q176', category: 'science', difficulty: 'expert', text: 'What is the process called by which a single cell divides to form two genetically identical daughter cells?', options: ['Meiosis', 'Mitosis', 'Osmosis', 'Apoptosis'], correctIndex: 1 },
  { id: 'q177', category: 'science', difficulty: 'expert', text: 'Which subatomic particle carries a negative electric charge?', options: ['Proton', 'Neutron', 'Electron', 'Positron'], correctIndex: 2 },
  { id: 'q178', category: 'science', difficulty: 'expert', text: 'What is the SI unit of electric current?', options: ['Volt', 'Watt', 'Ohm', 'Ampere'], correctIndex: 3 },
  { id: 'q179', category: 'science', difficulty: 'expert', text: 'Which scientist formulated the three fundamental laws of motion?', options: ['Galileo Galilei', 'Isaac Newton', 'Johannes Kepler', 'James Clerk Maxwell'], correctIndex: 1 },
  { id: 'q180', category: 'science', difficulty: 'expert', text: 'What term describes the distance that light travels in one year?', options: ['Parsec', 'Astronomical unit', 'Light-year', 'Megameter'], correctIndex: 2 },

  // food-drink
  { id: 'q033', category: 'food-drink', difficulty: 'medium', text: 'Which spirit is the base of a traditional Mojito?', options: ['Vodka', 'Gin', 'White rum', 'Tequila'], correctIndex: 2 },
  { id: 'q034', category: 'food-drink', difficulty: 'expert', text: 'What type of pastry is traditionally used to make a croissant?', options: ['Shortcrust', 'Puff pastry', 'Filo pastry', 'Laminated dough'], correctIndex: 3 },
  { id: 'q035', category: 'food-drink', difficulty: 'easy', text: 'Which country is the origin of tequila?', options: ['Spain', 'Mexico', 'Brazil', 'Cuba'], correctIndex: 1 },
  { id: 'q036', category: 'food-drink', difficulty: 'easy', text: 'What is the main ingredient in guacamole?', options: ['Tomato', 'Avocado', 'Lime', 'Onion'], correctIndex: 1 },
  { id: 'q037', category: 'food-drink', difficulty: 'medium', text: 'Champagne must come from which region to bear that name?', options: ['Bordeaux', 'Provence', 'Champagne', 'Loire Valley'], correctIndex: 2 },
  { id: 'q038', category: 'food-drink', difficulty: 'easy', text: 'Which cheese is traditionally used in a classic Margherita pizza?', options: ['Cheddar', 'Mozzarella', 'Parmesan', 'Gouda'], correctIndex: 1 },
  { id: 'q039', category: 'food-drink', difficulty: 'medium', text: 'What is the main alcohol in a classic Old Fashioned cocktail?', options: ['Rum', 'Gin', 'Whiskey', 'Brandy'], correctIndex: 2 },
  { id: 'q040', category: 'food-drink', difficulty: 'easy', text: 'Sushi originated in which country?', options: ['China', 'Korea', 'Japan', 'Thailand'], correctIndex: 2 },
  { id: 'q089', category: 'food-drink', difficulty: 'hard', text: 'Which country is the largest producer of coffee in the world?', options: ['Colombia', 'Vietnam', 'Brazil', 'Ethiopia'], correctIndex: 2 },
  { id: 'q090', category: 'food-drink', difficulty: 'easy', text: 'What is the main ingredient in traditional hummus?', options: ['Lentils', 'Chickpeas', 'Black beans', 'Fava beans'], correctIndex: 1 },
  { id: 'q091', category: 'food-drink', difficulty: 'hard', text: 'Which spirit is distilled from agave?', options: ['Rum', 'Vodka', 'Tequila', 'Gin'], correctIndex: 2 },
  { id: 'q092', category: 'food-drink', difficulty: 'expert', text: 'What type of pasta is shaped like small rice grains?', options: ['Orzo', 'Penne', 'Fusilli', 'Farfalle'], correctIndex: 0 },
  { id: 'q093', category: 'food-drink', difficulty: 'medium', text: 'Which fruit is used to make traditional guacamole turn brown if exposed to air?', options: ['Lime', 'Avocado', 'Tomato', 'Onion'], correctIndex: 1 },
  { id: 'q094', category: 'food-drink', difficulty: 'expert', text: 'A "negroni" cocktail combines gin, Campari, and which other ingredient?', options: ['Sweet vermouth', 'Tonic water', 'Triple sec', 'Dry vermouth'], correctIndex: 0 },
  { id: 'q095', category: 'food-drink', difficulty: 'hard', text: 'Which country is famous for originating the dish paella?', options: ['Italy', 'Portugal', 'Spain', 'Greece'], correctIndex: 2 },
  { id: 'q096', category: 'food-drink', difficulty: 'hard', text: 'What is the primary grain used to brew most beer?', options: ['Wheat', 'Rice', 'Barley', 'Corn'], correctIndex: 2 },
  { id: 'q097', category: 'food-drink', difficulty: 'hard', text: 'Which cheese is traditionally used in a classic Greek salad?', options: ['Mozzarella', 'Feta', 'Halloumi', 'Ricotta'], correctIndex: 1 },
  { id: 'q098', category: 'food-drink', difficulty: 'medium', text: 'What is the key spirit in a classic daiquiri?', options: ['Vodka', 'Gin', 'Rum', 'Whiskey'], correctIndex: 2 },
  { id: 'q099', category: 'food-drink', difficulty: 'expert', text: 'Which country is credited with inventing pizza in its modern form?', options: ['Greece', 'Italy', 'France', 'Turkey'], correctIndex: 1 },
  { id: 'q100', category: 'food-drink', difficulty: 'expert', text: 'What is the main ingredient in traditional miso soup?', options: ['Soybean paste', 'Seaweed only', 'Rice vinegar', 'Coconut milk'], correctIndex: 0 },
  { id: 'q181', category: 'food-drink', difficulty: 'easy', text: 'What is the main ingredient used to make traditional bread?', options: ['Sugar', 'Flour', 'Butter', 'Cornmeal'], correctIndex: 1 },
  { id: 'q182', category: 'food-drink', difficulty: 'easy', text: 'Which fruit is fermented to produce wine?', options: ['Apples', 'Grapes', 'Berries', 'Plums'], correctIndex: 1 },
  { id: 'q183', category: 'food-drink', difficulty: 'easy', text: 'What type of beverage is "Earl Grey"?', options: ['Coffee', 'Tea', 'Juice', 'Liqueur'], correctIndex: 1 },
  { id: 'q184', category: 'food-drink', difficulty: 'easy', text: 'Which vegetable is the main ingredient in classic French fries?', options: ['Sweet potato', 'Potato', 'Parsnip', 'Carrot'], correctIndex: 1 },
  { id: 'q185', category: 'food-drink', difficulty: 'easy', text: 'What is the main ingredient used to make traditional cheese?', options: ['Water', 'Milk', 'Cream', 'Butter'], correctIndex: 1 },
  { id: 'q186', category: 'food-drink', difficulty: 'medium', text: 'Which spirit is the base of a classic Martini cocktail?', options: ['Vodka', 'Gin', 'Rum', 'Tequila'], correctIndex: 1 },
  { id: 'q187', category: 'food-drink', difficulty: 'medium', text: 'Which soft cheese is the key ingredient in traditional tiramisu?', options: ['Ricotta', 'Cream cheese', 'Mascarpone', 'Brie'], correctIndex: 2 },
  { id: 'q188', category: 'food-drink', difficulty: 'medium', text: 'In its modern laminated form, the croissant is most associated with which country?', options: ['Austria', 'France', 'Belgium', 'Switzerland'], correctIndex: 1 },
  { id: 'q189', category: 'food-drink', difficulty: 'medium', text: 'Which ingredient is traditionally used in classic Caesar salad dressing for its salty, savory flavor?', options: ['Capers', 'Anchovies', 'Olives', 'Sardines'], correctIndex: 1 },
  { id: 'q190', category: 'food-drink', difficulty: 'medium', text: 'Which spice, derived from the crocus flower, is the most expensive by weight?', options: ['Vanilla', 'Cardamom', 'Saffron', 'Cinnamon'], correctIndex: 2 },
  { id: 'q191', category: 'food-drink', difficulty: 'hard', text: 'Which country is the largest producer of wine by volume?', options: ['France', 'Spain', 'Italy', 'United States'], correctIndex: 2 },
  { id: 'q192', category: 'food-drink', difficulty: 'hard', text: 'Which grain is fermented to produce traditional Japanese sake?', options: ['Wheat', 'Barley', 'Rice', 'Corn'], correctIndex: 2 },
  { id: 'q193', category: 'food-drink', difficulty: 'hard', text: 'Which French dish consists of thinly sliced potatoes baked in cream and sometimes cheese?', options: ['Ratatouille', 'Gratin dauphinois', 'Cassoulet', 'Tartiflette'], correctIndex: 1 },
  { id: 'q194', category: 'food-drink', difficulty: 'hard', text: 'Which prized fungus, used in French cuisine, grows underground and is hunted with trained dogs or pigs?', options: ['Morel', 'Truffle', 'Chanterelle', 'Porcini'], correctIndex: 1 },
  { id: 'q195', category: 'food-drink', difficulty: 'hard', text: 'Which cocktail is made by combining vodka, coffee liqueur, and cream?', options: ['Espresso Martini', 'White Russian', 'Mudslide', 'Irish Coffee'], correctIndex: 1 },
  { id: 'q196', category: 'food-drink', difficulty: 'expert', text: 'What is the Japanese rice wine produced through a multiple fermentation process called?', options: ['Shochu', 'Sake', 'Mirin', 'Umeshu'], correctIndex: 1 },
  { id: 'q197', category: 'food-drink', difficulty: 'expert', text: 'In French cuisine, what term refers to a flavorful stock or broth used as the base for sauces and soups?', options: ['Roux', 'Fond', 'Mirepoix', 'Jus'], correctIndex: 1 },
  { id: 'q198', category: 'food-drink', difficulty: 'expert', text: 'What is the primary ingredient in the cold Spanish soup gazpacho?', options: ['Cucumber', 'Pepper', 'Tomato', 'Onion'], correctIndex: 2 },
  { id: 'q199', category: 'food-drink', difficulty: 'expert', text: 'Which cheese is traditionally melted on top of French onion soup gratinée?', options: ['Brie', 'Gruyère', 'Camembert', 'Roquefort'], correctIndex: 1 },
  { id: 'q200', category: 'food-drink', difficulty: 'expert', text: 'What is the French culinary term for the technique of slow-cooking meat submerged in its own fat?', options: ['Sous vide', 'Confit', 'Braise', 'Poach'], correctIndex: 1 },
]
